#ifndef ENCAPSULATION_GLOBAL_H
#define ENCAPSULATION_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(ENCAPSULATION_LIBRARY)
#  define ENCAPSULATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENCAPSULATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENCAPSULATION_GLOBAL_H

